image: maven:3.6.3-jdk-14

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  RELEASE_VERSION_REGEX: '^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}$'
  SNAPSHOT_VERSION_REGEX: '^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}-SNAPSHOT$'

cache:
  paths:
    - .m2/repository/
    - target/
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

.deploy:
  stage: deploy
  before_script:
    - echo "Executed by" $GITLAB_USER_NAME "on branch:" $CI_COMMIT_REF_NAME
    - export VERSION=$(cat pom.xml | grep "<version>" | head -1| cut -d">" -f2| cut -d"<" -f1)
    - if [[ !("$VERSION" =~ $REGEXP) ]]; then echo "Library version" $VERSION "is not valid"; exit 1; fi
  script:
    - mvn -DskipTests $MAVEN_CLI_OPTS deploy
    - echo "version" $VERSION "successfully deployed"

deploy release:
  extends: .deploy
  variables:
    REGEXP: '^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}$'
  only:
    - master

deploy snapshot:
  extends: .deploy
  variables:
    REGEXP: '^[0-9]{1,2}[.][0-9]{1,2}[.][0-9]{1,3}-SNAPSHOT$'
  only:
    - branches
    - merge_requests
  except:
    - master
